identifier: hades40
name: Hades40
type: keyboard
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
exposes:
  - i2c_oled
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
  - WS2812B
